# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\createdirs.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(761, 314)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 59, 651, 231))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.layoutWidget)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_2.addWidget(self.textBrowser)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 75))
        self.groupBox.setMaximumSize(QtCore.QSize(150, 16777215))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.enabledRb = QtWidgets.QRadioButton(self.groupBox)
        self.enabledRb.setGeometry(QtCore.QRect(10, 10, 141, 20))
        self.enabledRb.setChecked(True)
        self.enabledRb.setObjectName("enabledRb")
        self.disabledRb = QtWidgets.QRadioButton(self.groupBox)
        self.disabledRb.setGeometry(QtCore.QRect(10, 40, 141, 20))
        self.disabledRb.setObjectName("disabledRb")
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.createDirsBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.createDirsBtn.setEnabled(False)
        self.createDirsBtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.createDirsBtn.setObjectName("createDirsBtn")
        self.horizontalLayout.addWidget(self.createDirsBtn)
        self.createDirsYear = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.createDirsYear.sizePolicy().hasHeightForWidth())
        self.createDirsYear.setSizePolicy(sizePolicy)
        self.createDirsYear.setMaximumSize(QtCore.QSize(75, 16777215))
        self.createDirsYear.setObjectName("createDirsYear")
        self.createDirsYear.addItem("")
        self.createDirsYear.addItem("")
        self.createDirsYear.addItem("")
        self.createDirsYear.addItem("")
        self.createDirsYear.addItem("")
        self.createDirsYear.addItem("")
        self.createDirsYear.addItem("")
        self.horizontalLayout.addWidget(self.createDirsYear)
        self.createDirsMonth = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.createDirsMonth.sizePolicy().hasHeightForWidth())
        self.createDirsMonth.setSizePolicy(sizePolicy)
        self.createDirsMonth.setMaximumSize(QtCore.QSize(85, 16777215))
        self.createDirsMonth.setObjectName("createDirsMonth")
        self.createDirsMonth.addItem("")
        self.createDirsMonth.addItem("")
        self.createDirsMonth.addItem("")
        self.createDirsMonth.addItem("")
        self.createDirsMonth.addItem("")
        self.createDirsMonth.addItem("")
        self.createDirsMonth.addItem("")
        self.createDirsMonth.addItem("")
        self.createDirsMonth.addItem("")
        self.createDirsMonth.addItem("")
        self.createDirsMonth.addItem("")
        self.createDirsMonth.addItem("")
        self.horizontalLayout.addWidget(self.createDirsMonth)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.textBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<h1 style=\" margin-top:18px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Create directories</span></h1>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">This task is automatic based on your system date. If your system date is strangely set, you can disable automatic creation and control the directory creation yourself.</span></p></body></html>"))
        self.enabledRb.setText(_translate("Dialog", "Autogen Enabled"))
        self.disabledRb.setText(_translate("Dialog", "Autogen Disabled"))
        self.label_10.setText(_translate("Dialog", "Create journal file directories for the month of ...."))
        self.createDirsBtn.setText(_translate("Dialog", "Create Dirs"))
        self.createDirsYear.setItemText(0, _translate("Dialog", "2019"))
        self.createDirsYear.setItemText(1, _translate("Dialog", "2020"))
        self.createDirsYear.setItemText(2, _translate("Dialog", "2021"))
        self.createDirsYear.setItemText(3, _translate("Dialog", "2022"))
        self.createDirsYear.setItemText(4, _translate("Dialog", "2023"))
        self.createDirsYear.setItemText(5, _translate("Dialog", "2024"))
        self.createDirsYear.setItemText(6, _translate("Dialog", "2025"))
        self.createDirsMonth.setItemText(0, _translate("Dialog", "January"))
        self.createDirsMonth.setItemText(1, _translate("Dialog", "February"))
        self.createDirsMonth.setItemText(2, _translate("Dialog", "March"))
        self.createDirsMonth.setItemText(3, _translate("Dialog", "April"))
        self.createDirsMonth.setItemText(4, _translate("Dialog", "May"))
        self.createDirsMonth.setItemText(5, _translate("Dialog", "June"))
        self.createDirsMonth.setItemText(6, _translate("Dialog", "July"))
        self.createDirsMonth.setItemText(7, _translate("Dialog", "August"))
        self.createDirsMonth.setItemText(8, _translate("Dialog", "September"))
        self.createDirsMonth.setItemText(9, _translate("Dialog", "October"))
        self.createDirsMonth.setItemText(10, _translate("Dialog", "November"))
        self.createDirsMonth.setItemText(11, _translate("Dialog", "December"))
