# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'statisticshub2.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1444, 1580)
        self.gridLayout_6 = QtWidgets.QGridLayout(Form)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.widget_3 = QtWidgets.QWidget(Form)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.widget = QtWidgets.QWidget(self.widget_3)
        self.widget.setMinimumSize(QtCore.QSize(1400, 200))
        self.widget.setMaximumSize(QtCore.QSize(1500, 200))
        self.widget.setObjectName("widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.symbolEdit = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.symbolEdit.setFont(font)
        self.symbolEdit.setToolTipDuration(20)
        self.symbolEdit.setText("")
        self.symbolEdit.setObjectName("symbolEdit")
        self.horizontalLayout.addWidget(self.symbolEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.sideCB = QtWidgets.QComboBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sideCB.setFont(font)
        self.sideCB.setObjectName("sideCB")
        self.sideCB.addItem("")
        self.sideCB.addItem("")
        self.sideCB.addItem("")
        self.horizontalLayout_2.addWidget(self.sideCB)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2, 0, QtCore.Qt.AlignTop)
        self.tagsListWidget = QtWidgets.QListWidget(self.widget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.tagsListWidget.setFont(font)
        self.tagsListWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.tagsListWidget.setObjectName("tagsListWidget")
        item = QtWidgets.QListWidgetItem()
        self.tagsListWidget.addItem(item)
        self.horizontalLayout_3.addWidget(self.tagsListWidget)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_8.addLayout(self.verticalLayout_2)
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setStyleSheet("color: rgb(77, 33, 255);\n"
"padding-left: 10px;\n"
"padding-right:10px;")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_8.addWidget(self.line)
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tradesBySetsRB = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tradesBySetsRB.setFont(font)
        self.tradesBySetsRB.setObjectName("tradesBySetsRB")
        self.verticalLayout.addWidget(self.tradesBySetsRB)
        self.tradesByTimeRB = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tradesByTimeRB.setFont(font)
        self.tradesByTimeRB.setObjectName("tradesByTimeRB")
        self.verticalLayout.addWidget(self.tradesByTimeRB)
        self.groupTradesWidget = QtWidgets.QWidget(self.groupBox)
        self.groupTradesWidget.setStyleSheet("background-color: rgb(255, 255, 228);\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(221, 232, 118, 255), stop:1 rgba(255, 255, 255, 255));")
        self.groupTradesWidget.setObjectName("groupTradesWidget")
        self.verticalLayout.addWidget(self.groupTradesWidget)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_8.addWidget(self.groupBox)
        self.line_2 = QtWidgets.QFrame(self.widget)
        self.line_2.setStyleSheet("color: rgb(77, 33, 255);\n"
"padding-left: 10px;\n"
"padding-right:10px;")
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_8.addWidget(self.line_2)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(325, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(350, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.strategyListWidget = QtWidgets.QListWidget(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.strategyListWidget.setFont(font)
        self.strategyListWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.strategyListWidget.setObjectName("strategyListWidget")
        item = QtWidgets.QListWidgetItem()
        self.strategyListWidget.addItem(item)
        self.gridLayout.addWidget(self.strategyListWidget, 0, 0, 1, 1)
        self.horizontalLayout_8.addWidget(self.groupBox_2)
        self.line_3 = QtWidgets.QFrame(self.widget)
        self.line_3.setStyleSheet("color: rgb(77, 33, 255);\n"
"padding-left: 10px;\n"
"padding-right:10px;")
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_8.addWidget(self.line_3)
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.dateRange30Cbox = QtWidgets.QCheckBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dateRange30Cbox.setFont(font)
        self.dateRange30Cbox.setObjectName("dateRange30Cbox")
        self.verticalLayout_4.addWidget(self.dateRange30Cbox)
        self.dateRange60Cbox = QtWidgets.QCheckBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dateRange60Cbox.setFont(font)
        self.dateRange60Cbox.setObjectName("dateRange60Cbox")
        self.verticalLayout_4.addWidget(self.dateRange60Cbox)
        self.dateRange90Cbox = QtWidgets.QCheckBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dateRange90Cbox.setFont(font)
        self.dateRange90Cbox.setObjectName("dateRange90Cbox")
        self.verticalLayout_4.addWidget(self.dateRange90Cbox)
        self.horizontalLayout_6.addLayout(self.verticalLayout_4)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(118, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.selectStartBtn = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectStartBtn.sizePolicy().hasHeightForWidth())
        self.selectStartBtn.setSizePolicy(sizePolicy)
        self.selectStartBtn.setMaximumSize(QtCore.QSize(20, 25))
        self.selectStartBtn.setObjectName("selectStartBtn")
        self.horizontalLayout_4.addWidget(self.selectStartBtn)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.selectStartDate = QtWidgets.QDateEdit(self.groupBox_3)
        self.selectStartDate.setMaximumSize(QtCore.QSize(173, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.selectStartDate.setFont(font)
        self.selectStartDate.setObjectName("selectStartDate")
        self.verticalLayout_7.addWidget(self.selectStartDate)
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_7.addWidget(self.label_4)
        self.horizontalLayout_6.addLayout(self.verticalLayout_7)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(108, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.selectEndBtn = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectEndBtn.sizePolicy().hasHeightForWidth())
        self.selectEndBtn.setSizePolicy(sizePolicy)
        self.selectEndBtn.setMaximumSize(QtCore.QSize(20, 25))
        self.selectEndBtn.setObjectName("selectEndBtn")
        self.horizontalLayout_5.addWidget(self.selectEndBtn)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.selectEndDate = QtWidgets.QDateEdit(self.groupBox_3)
        self.selectEndDate.setMaximumSize(QtCore.QSize(173, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.selectEndDate.setFont(font)
        self.selectEndDate.setObjectName("selectEndDate")
        self.verticalLayout_6.addWidget(self.selectEndDate)
        self.verticalLayout_5.addLayout(self.verticalLayout_6)
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.horizontalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_9.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.selectAccount = QtWidgets.QComboBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.selectAccount.setFont(font)
        self.selectAccount.setObjectName("selectAccount")
        self.selectAccount.addItem("")
        self.horizontalLayout_7.addWidget(self.selectAccount)
        self.verticalLayout_9.addLayout(self.horizontalLayout_7)
        self.gridLayout_2.addLayout(self.verticalLayout_9, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 1, 1, 1)
        self.horizontalLayout_8.addWidget(self.groupBox_3)
        self.gridLayout_4.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.widget, 0, 0, 1, 1)
        self.chartstack = QtWidgets.QWidget(self.widget_3)
        self.chartstack.setStyleSheet("background-color: rgb(6, 51, 198);")
        self.chartstack.setObjectName("chartstack")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.chartstack)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.chartstack1 = QtWidgets.QWidget(self.chartstack)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chartstack1.sizePolicy().hasHeightForWidth())
        self.chartstack1.setSizePolicy(sizePolicy)
        self.chartstack1.setStyleSheet("background-color: rgb(106, 255, 128);")
        self.chartstack1.setObjectName("chartstack1")
        self.gridLayout_7.addWidget(self.chartstack1, 0, 0, 1, 1)
        self.chartstack2 = QtWidgets.QWidget(self.chartstack)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chartstack2.sizePolicy().hasHeightForWidth())
        self.chartstack2.setSizePolicy(sizePolicy)
        self.chartstack2.setStyleSheet("background-color: rgb(106, 255, 128);")
        self.chartstack2.setObjectName("chartstack2")
        self.gridLayout_7.addWidget(self.chartstack2, 1, 0, 1, 1)
        self.chartstack3 = QtWidgets.QWidget(self.chartstack)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chartstack3.sizePolicy().hasHeightForWidth())
        self.chartstack3.setSizePolicy(sizePolicy)
        self.chartstack3.setStyleSheet("background-color: rgb(106, 255, 128);")
        self.chartstack3.setObjectName("chartstack3")
        self.gridLayout_7.addWidget(self.chartstack3, 2, 0, 1, 1)
        self.gridLayout_5.addWidget(self.chartstack, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.widget_3, 0, 0, 1, 1)
        self.widget1 = QtWidgets.QWidget(Form)
        self.widget1.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setToolTip(_translate("Form", "<h1>Filter by ticker</h1>\n"
"Enter a comma seperated list of tickers to view"))
        self.label.setText(_translate("Form", "Symbol:"))
        self.symbolEdit.setToolTip(_translate("Form", "<h1>Filter by ticker</h1>\n"
"Enter a comma seperated list of tickers to view"))
        self.label_3.setText(_translate("Form", "Side"))
        self.sideCB.setItemText(0, _translate("Form", "Both"))
        self.sideCB.setItemText(1, _translate("Form", "Long"))
        self.sideCB.setItemText(2, _translate("Form", "Short"))
        self.label_2.setText(_translate("Form", "Tags"))
        self.tagsListWidget.setToolTip(_translate("Form", "<h1>Select Trades with specific tags only</h1>\n"
"Select one or more tags to filter by tag(s)"))
        __sortingEnabled = self.tagsListWidget.isSortingEnabled()
        self.tagsListWidget.setSortingEnabled(False)
        item = self.tagsListWidget.item(0)
        item.setText(_translate("Form", "A Tag"))
        self.tagsListWidget.setSortingEnabled(__sortingEnabled)
        self.groupBox.setTitle(_translate("Form", "Group trades"))
        self.tradesBySetsRB.setText(_translate("Form", "In Sets by number of trades"))
        self.tradesByTimeRB.setText(_translate("Form", "By time"))
        self.groupBox_2.setTitle(_translate("Form", "Select Strategies"))
        self.strategyListWidget.setToolTip(_translate("Form", "<h1>Select Trades with specific tags only</h1>\n"
"Select one or more tags to filter by tag(s)"))
        __sortingEnabled = self.strategyListWidget.isSortingEnabled()
        self.strategyListWidget.setSortingEnabled(False)
        item = self.strategyListWidget.item(0)
        item.setText(_translate("Form", "A Strategy"))
        self.strategyListWidget.setSortingEnabled(__sortingEnabled)
        self.groupBox_3.setTitle(_translate("Form", "Select Date Range"))
        self.dateRange30Cbox.setText(_translate("Form", "30 Days"))
        self.dateRange60Cbox.setText(_translate("Form", "60 Days"))
        self.dateRange90Cbox.setText(_translate("Form", "90 Days"))
        self.selectStartBtn.setText(_translate("Form", "..."))
        self.selectStartDate.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">When databse is checked, changing the date will load trades that are in the database. Use the calendar widget by clicking the button to the right to skip to a specific date.</span></p></body></html>"))
        self.label_4.setText(_translate("Form", "Start Date"))
        self.selectEndBtn.setText(_translate("Form", "..."))
        self.selectEndDate.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">When databse is checked, changing the date will load trades that are in the database. Use the calendar widget by clicking the button to the right to skip to a specific date.</span></p></body></html>"))
        self.label_5.setText(_translate("Form", "End Date"))
        self.label_6.setText(_translate("Form", "Select Account"))
        self.selectAccount.setItemText(0, _translate("Form", "All Accounts"))
