# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\filesettings.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(853, 386)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(670, 40, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.theDateCbox = QtWidgets.QCheckBox(Dialog)
        self.theDateCbox.setGeometry(QtCore.QRect(630, 320, 201, 20))
        self.theDateCbox.setChecked(False)
        self.theDateCbox.setObjectName("theDateCbox")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(31, 41, 574, 315))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.journalBtn = QtWidgets.QPushButton(self.widget)
        self.journalBtn.setObjectName("journalBtn")
        self.horizontalLayout.addWidget(self.journalBtn)
        self.journal = QtWidgets.QLineEdit(self.widget)
        self.journal.setMinimumSize(QtCore.QSize(300, 0))
        self.journal.setObjectName("journal")
        self.horizontalLayout.addWidget(self.journal)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.schemeBtn = QtWidgets.QPushButton(self.widget)
        self.schemeBtn.setObjectName("schemeBtn")
        self.horizontalLayout_2.addWidget(self.schemeBtn)
        self.scheme = QtWidgets.QLineEdit(self.widget)
        self.scheme.setMinimumSize(QtCore.QSize(300, 0))
        self.scheme.setObjectName("scheme")
        self.horizontalLayout_2.addWidget(self.scheme)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.schemeLbl = QtWidgets.QLabel(self.widget)
        self.schemeLbl.setObjectName("schemeLbl")
        self.verticalLayout.addWidget(self.schemeLbl)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.dasInfileBtn = QtWidgets.QPushButton(self.widget)
        self.dasInfileBtn.setObjectName("dasInfileBtn")
        self.horizontalLayout_3.addWidget(self.dasInfileBtn)
        self.dasInfile = QtWidgets.QLineEdit(self.widget)
        self.dasInfile.setMinimumSize(QtCore.QSize(300, 0))
        self.dasInfile.setObjectName("dasInfile")
        self.horizontalLayout_3.addWidget(self.dasInfile)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.dasInfile2Btn = QtWidgets.QPushButton(self.widget)
        self.dasInfile2Btn.setObjectName("dasInfile2Btn")
        self.horizontalLayout_4.addWidget(self.dasInfile2Btn)
        self.dasInfile2 = QtWidgets.QLineEdit(self.widget)
        self.dasInfile2.setMinimumSize(QtCore.QSize(300, 0))
        self.dasInfile2.setObjectName("dasInfile2")
        self.horizontalLayout_4.addWidget(self.dasInfile2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ibInfileLbl = QtWidgets.QLabel(self.widget)
        self.ibInfileLbl.setObjectName("ibInfileLbl")
        self.horizontalLayout_5.addWidget(self.ibInfileLbl)
        self.ibInfile = QtWidgets.QLineEdit(self.widget)
        self.ibInfile.setObjectName("ibInfile")
        self.horizontalLayout_5.addWidget(self.ibInfile)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.outdirLbl = QtWidgets.QLabel(self.widget)
        self.outdirLbl.setObjectName("outdirLbl")
        self.horizontalLayout_6.addWidget(self.outdirLbl)
        self.outdir = QtWidgets.QLineEdit(self.widget)
        self.outdir.setMinimumSize(QtCore.QSize(300, 0))
        self.outdir.setObjectName("outdir")
        self.horizontalLayout_6.addWidget(self.outdir)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.explainDateLbl = QtWidgets.QLabel(self.widget)
        self.explainDateLbl.setObjectName("explainDateLbl")
        self.verticalLayout.addWidget(self.explainDateLbl)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.theDateBtn = QtWidgets.QPushButton(self.widget)
        self.theDateBtn.setObjectName("theDateBtn")
        self.horizontalLayout_7.addWidget(self.theDateBtn)
        self.theDate = QtWidgets.QDateEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.theDate.sizePolicy().hasHeightForWidth())
        self.theDate.setSizePolicy(sizePolicy)
        self.theDate.setObjectName("theDate")
        self.horizontalLayout_7.addWidget(self.theDate)
        self.verticalLayout.addLayout(self.horizontalLayout_7)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Commit All"))
        self.theDateCbox.setText(_translate("Dialog", "Set today when program opens."))
        self.journalBtn.setText(_translate("Dialog", "Journal Directory"))
        self.journal.setText(_translate("Dialog", "C:/traders/journal"))
        self.label.setText(_translate("Dialog", "Directory Naming Scheme. Enter to commit"))
        self.schemeBtn.setText(_translate("Dialog", "Set Default"))
        self.scheme.setToolTip(_translate("Dialog", "<html><head/><body><p>Use the date variables as seen in the default naming scheme and see the result below. Please retain a month/day directory structure. Both directories should sort alpa-numerically. After editing press enter to update the naming scheme.</p></body></html>"))
        self.scheme.setText(_translate("Dialog", "_{Year}{month}_{MONTH}/_{month}{day}_{DAY}/"))
        self.schemeLbl.setText(_translate("Dialog", "_201901_January/_0114_Monday"))
        self.dasInfileBtn.setToolTip(_translate("Dialog", "<html><head/><body><p>Click this button to return the edit box to just the file name.</p></body></html>"))
        self.dasInfileBtn.setText(_translate("Dialog", "DAS Trades export"))
        self.dasInfile.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Enter only the filename. Press enter to see the resulting pathfile name. The color will indicate if the file exists or not.</span></p></body></html>"))
        self.dasInfile.setText(_translate("Dialog", "trades.csv"))
        self.dasInfile2Btn.setText(_translate("Dialog", "DAS positions export"))
        self.dasInfile2.setText(_translate("Dialog", "positions.csv"))
        self.ibInfileLbl.setText(_translate("Dialog", "Default IB Activity Statement"))
        self.ibInfile.setText(_translate("Dialog", "Activity{*}.html"))
        self.outdirLbl.setText(_translate("Dialog", "Default out directory"))
        self.outdir.setText(_translate("Dialog", "out/"))
        self.explainDateLbl.setText(_translate("Dialog", "Date will be used to locate daily directories and set dates if missing (DAS trade)"))
        self.theDateBtn.setText(_translate("Dialog", "Set to Today"))
        self.theDate.setToolTip(_translate("Dialog", "<html><head/><body><p>Date will be used to locate the desired directories for input files. It wil also be used if the input files are missing dates. This is the case for the DAS trades export file, aka trades.csv.</p></body></html>"))


