# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\summaryform.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2334, 1567)
        MainWindow.setMouseTracking(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(70, 110, 2258, 673))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.title = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title.sizePolicy().hasHeightForWidth())
        self.title.setSizePolicy(sizePolicy)
        self.title.setMinimumSize(QtCore.QSize(330, 0))
        self.title.setMaximumSize(QtCore.QSize(350, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(24)
        self.title.setFont(font)
        self.title.setStyleSheet("border: 1px solid black")
        self.title.setObjectName("title")
        self.gridLayout_2.addWidget(self.title, 0, 0, 1, 3)
        self.plHead = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plHead.sizePolicy().hasHeightForWidth())
        self.plHead.setSizePolicy(sizePolicy)
        self.plHead.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.plHead.setFont(font)
        self.plHead.setStyleSheet("border: 1px solid black")
        self.plHead.setObjectName("plHead")
        self.gridLayout_2.addWidget(self.plHead, 1, 0, 1, 1)
        self.pl = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pl.sizePolicy().hasHeightForWidth())
        self.pl.setSizePolicy(sizePolicy)
        self.pl.setMinimumSize(QtCore.QSize(250, 0))
        self.pl.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.pl.setFont(font)
        self.pl.setStyleSheet("border: 1px solid black")
        self.pl.setObjectName("pl")
        self.gridLayout_2.addWidget(self.pl, 1, 1, 1, 2)
        self.startHead = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startHead.sizePolicy().hasHeightForWidth())
        self.startHead.setSizePolicy(sizePolicy)
        self.startHead.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.startHead.setFont(font)
        self.startHead.setStyleSheet("border: 1px solid black")
        self.startHead.setObjectName("startHead")
        self.gridLayout_2.addWidget(self.startHead, 2, 0, 1, 1)
        self.start = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start.sizePolicy().hasHeightForWidth())
        self.start.setSizePolicy(sizePolicy)
        self.start.setMinimumSize(QtCore.QSize(250, 0))
        self.start.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.start.setFont(font)
        self.start.setStyleSheet("border: 1px solid black")
        self.start.setObjectName("start")
        self.gridLayout_2.addWidget(self.start, 2, 1, 1, 2)
        self.durHead = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.durHead.sizePolicy().hasHeightForWidth())
        self.durHead.setSizePolicy(sizePolicy)
        self.durHead.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.durHead.setFont(font)
        self.durHead.setStyleSheet("border: 1px solid black")
        self.durHead.setObjectName("durHead")
        self.gridLayout_2.addWidget(self.durHead, 3, 0, 1, 1)
        self.dur = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dur.sizePolicy().hasHeightForWidth())
        self.dur.setSizePolicy(sizePolicy)
        self.dur.setMinimumSize(QtCore.QSize(250, 0))
        self.dur.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.dur.setFont(font)
        self.dur.setStyleSheet("border: 1px solid black")
        self.dur.setObjectName("dur")
        self.gridLayout_2.addWidget(self.dur, 3, 1, 1, 2)
        self.posHead = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.posHead.sizePolicy().hasHeightForWidth())
        self.posHead.setSizePolicy(sizePolicy)
        self.posHead.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.posHead.setFont(font)
        self.posHead.setStyleSheet("border: 1px solid black")
        self.posHead.setObjectName("posHead")
        self.gridLayout_2.addWidget(self.posHead, 4, 0, 1, 1)
        self.pos = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pos.sizePolicy().hasHeightForWidth())
        self.pos.setSizePolicy(sizePolicy)
        self.pos.setMinimumSize(QtCore.QSize(250, 0))
        self.pos.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.pos.setFont(font)
        self.pos.setStyleSheet("border: 1px solid black")
        self.pos.setObjectName("pos")
        self.gridLayout_2.addWidget(self.pos, 4, 1, 1, 2)
        self.mktHead = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mktHead.sizePolicy().hasHeightForWidth())
        self.mktHead.setSizePolicy(sizePolicy)
        self.mktHead.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.mktHead.setFont(font)
        self.mktHead.setStyleSheet("border: 1px solid black")
        self.mktHead.setObjectName("mktHead")
        self.gridLayout_2.addWidget(self.mktHead, 5, 0, 1, 1)
        self.mkt = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mkt.sizePolicy().hasHeightForWidth())
        self.mkt.setSizePolicy(sizePolicy)
        self.mkt.setMinimumSize(QtCore.QSize(250, 0))
        self.mkt.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.mkt.setFont(font)
        self.mkt.setStyleSheet("border: 1px solid black")
        self.mkt.setObjectName("mkt")
        self.gridLayout_2.addWidget(self.mkt, 5, 1, 1, 2)
        self.targHead = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.targHead.sizePolicy().hasHeightForWidth())
        self.targHead.setSizePolicy(sizePolicy)
        self.targHead.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.targHead.setFont(font)
        self.targHead.setStyleSheet("border: 1px solid black")
        self.targHead.setObjectName("targHead")
        self.gridLayout_2.addWidget(self.targHead, 6, 0, 1, 1)
        self.targ = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.targ.sizePolicy().hasHeightForWidth())
        self.targ.setSizePolicy(sizePolicy)
        self.targ.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.targ.setFont(font)
        self.targ.setObjectName("targ")
        self.gridLayout_2.addWidget(self.targ, 6, 1, 1, 1)
        self.targDiff = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.targDiff.sizePolicy().hasHeightForWidth())
        self.targDiff.setSizePolicy(sizePolicy)
        self.targDiff.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.targDiff.setFont(font)
        self.targDiff.setStyleSheet("border: 1px solid black")
        self.targDiff.setText("")
        self.targDiff.setObjectName("targDiff")
        self.gridLayout_2.addWidget(self.targDiff, 6, 2, 1, 1)
        self.stopHead = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopHead.sizePolicy().hasHeightForWidth())
        self.stopHead.setSizePolicy(sizePolicy)
        self.stopHead.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.stopHead.setFont(font)
        self.stopHead.setStyleSheet("border: 1px solid black")
        self.stopHead.setObjectName("stopHead")
        self.gridLayout_2.addWidget(self.stopHead, 7, 0, 1, 1)
        self.stop = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop.sizePolicy().hasHeightForWidth())
        self.stop.setSizePolicy(sizePolicy)
        self.stop.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.stop.setFont(font)
        self.stop.setObjectName("stop")
        self.gridLayout_2.addWidget(self.stop, 7, 1, 1, 1)
        self.stopDiff = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopDiff.sizePolicy().hasHeightForWidth())
        self.stopDiff.setSizePolicy(sizePolicy)
        self.stopDiff.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.stopDiff.setFont(font)
        self.stopDiff.setStyleSheet("border: 1px solid black")
        self.stopDiff.setText("")
        self.stopDiff.setObjectName("stopDiff")
        self.gridLayout_2.addWidget(self.stopDiff, 7, 2, 1, 1)
        self.rrHead = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rrHead.sizePolicy().hasHeightForWidth())
        self.rrHead.setSizePolicy(sizePolicy)
        self.rrHead.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.rrHead.setFont(font)
        self.rrHead.setStyleSheet("border: 1px solid black")
        self.rrHead.setObjectName("rrHead")
        self.gridLayout_2.addWidget(self.rrHead, 8, 0, 1, 1)
        self.rr = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rr.sizePolicy().hasHeightForWidth())
        self.rr.setSizePolicy(sizePolicy)
        self.rr.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.rr.setFont(font)
        self.rr.setStyleSheet("border: 1px solid black")
        self.rr.setText("")
        self.rr.setObjectName("rr")
        self.gridLayout_2.addWidget(self.rr, 8, 1, 1, 1)
        self.maxHead = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxHead.sizePolicy().hasHeightForWidth())
        self.maxHead.setSizePolicy(sizePolicy)
        self.maxHead.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.maxHead.setFont(font)
        self.maxHead.setStyleSheet("border: 1px solid black")
        self.maxHead.setObjectName("maxHead")
        self.gridLayout_2.addWidget(self.maxHead, 9, 0, 1, 1)
        self.maxLoss = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxLoss.sizePolicy().hasHeightForWidth())
        self.maxLoss.setSizePolicy(sizePolicy)
        self.maxLoss.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.maxLoss.setFont(font)
        self.maxLoss.setStyleSheet("border: 1px solid black")
        self.maxLoss.setText("")
        self.maxLoss.setObjectName("maxLoss")
        self.gridLayout_2.addWidget(self.maxLoss, 9, 1, 1, 1)
        self.lostHead = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lostHead.sizePolicy().hasHeightForWidth())
        self.lostHead.setSizePolicy(sizePolicy)
        self.lostHead.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lostHead.setFont(font)
        self.lostHead.setStyleSheet("border: 1px solid black")
        self.lostHead.setObjectName("lostHead")
        self.gridLayout_2.addWidget(self.lostHead, 10, 0, 1, 1)
        self.lost = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lost.sizePolicy().hasHeightForWidth())
        self.lost.setSizePolicy(sizePolicy)
        self.lost.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.lost.setFont(font)
        self.lost.setObjectName("lost")
        self.gridLayout_2.addWidget(self.lost, 10, 1, 1, 1)
        self.sumNote = QtWidgets.QTextEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sumNote.sizePolicy().hasHeightForWidth())
        self.sumNote.setSizePolicy(sizePolicy)
        self.sumNote.setMaximumSize(QtCore.QSize(430, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sumNote.setFont(font)
        self.sumNote.setObjectName("sumNote")
        self.gridLayout_2.addWidget(self.sumNote, 11, 0, 1, 3)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.entry2 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry2.sizePolicy().hasHeightForWidth())
        self.entry2.setSizePolicy(sizePolicy)
        self.entry2.setStyleSheet("border: 1px solid black")
        self.entry2.setText("")
        self.entry2.setObjectName("entry2")
        self.gridLayout_3.addWidget(self.entry2, 1, 2, 1, 1)
        self.pl8 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pl8.sizePolicy().hasHeightForWidth())
        self.pl8.setSizePolicy(sizePolicy)
        self.pl8.setStyleSheet("border: 1px solid black")
        self.pl8.setText("")
        self.pl8.setObjectName("pl8")
        self.gridLayout_3.addWidget(self.pl8, 6, 8, 1, 1)
        self.exit4 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exit4.sizePolicy().hasHeightForWidth())
        self.exit4.setSizePolicy(sizePolicy)
        self.exit4.setStyleSheet("border: 1px solid black")
        self.exit4.setText("")
        self.exit4.setObjectName("exit4")
        self.gridLayout_3.addWidget(self.exit4, 2, 4, 1, 1)
        self.account = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.account.sizePolicy().hasHeightForWidth())
        self.account.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(24)
        self.account.setFont(font)
        self.account.setStyleSheet("border: 1px solid black")
        self.account.setObjectName("account")
        self.gridLayout_3.addWidget(self.account, 0, 0, 1, 3)
        self.share1 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.share1.sizePolicy().hasHeightForWidth())
        self.share1.setSizePolicy(sizePolicy)
        self.share1.setStyleSheet("border: 1px solid black")
        self.share1.setText("")
        self.share1.setObjectName("share1")
        self.gridLayout_3.addWidget(self.share1, 4, 1, 1, 1)
        self.diffHead = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.diffHead.sizePolicy().hasHeightForWidth())
        self.diffHead.setSizePolicy(sizePolicy)
        self.diffHead.setStyleSheet("")
        self.diffHead.setObjectName("diffHead")
        self.gridLayout_3.addWidget(self.diffHead, 5, 0, 1, 1)
        self.shareHead = QtWidgets.QLabel(self.layoutWidget)
        self.shareHead.setStyleSheet("")
        self.shareHead.setObjectName("shareHead")
        self.gridLayout_3.addWidget(self.shareHead, 4, 0, 1, 1)
        self.pl1 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pl1.sizePolicy().hasHeightForWidth())
        self.pl1.setSizePolicy(sizePolicy)
        self.pl1.setStyleSheet("border: 1px solid black")
        self.pl1.setText("")
        self.pl1.setObjectName("pl1")
        self.gridLayout_3.addWidget(self.pl1, 6, 1, 1, 1)
        self.entry3 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry3.sizePolicy().hasHeightForWidth())
        self.entry3.setSizePolicy(sizePolicy)
        self.entry3.setStyleSheet("border: 1px solid black")
        self.entry3.setText("")
        self.entry3.setObjectName("entry3")
        self.gridLayout_3.addWidget(self.entry3, 1, 3, 1, 1)
        self.entry5 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry5.sizePolicy().hasHeightForWidth())
        self.entry5.setSizePolicy(sizePolicy)
        self.entry5.setStyleSheet("border: 1px solid black")
        self.entry5.setText("")
        self.entry5.setObjectName("entry5")
        self.gridLayout_3.addWidget(self.entry5, 1, 5, 1, 1)
        self.share4 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.share4.sizePolicy().hasHeightForWidth())
        self.share4.setSizePolicy(sizePolicy)
        self.share4.setStyleSheet("border: 1px solid black")
        self.share4.setText("")
        self.share4.setObjectName("share4")
        self.gridLayout_3.addWidget(self.share4, 4, 4, 1, 1)
        self.time7 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time7.sizePolicy().hasHeightForWidth())
        self.time7.setSizePolicy(sizePolicy)
        self.time7.setStyleSheet("border: 1px solid black")
        self.time7.setText("")
        self.time7.setObjectName("time7")
        self.gridLayout_3.addWidget(self.time7, 3, 7, 1, 1)
        self.diff8 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.diff8.sizePolicy().hasHeightForWidth())
        self.diff8.setSizePolicy(sizePolicy)
        self.diff8.setStyleSheet("border: 1px solid black")
        self.diff8.setText("")
        self.diff8.setObjectName("diff8")
        self.gridLayout_3.addWidget(self.diff8, 5, 8, 1, 1)
        self.entry8 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry8.sizePolicy().hasHeightForWidth())
        self.entry8.setSizePolicy(sizePolicy)
        self.entry8.setStyleSheet("border: 1px solid black")
        self.entry8.setText("")
        self.entry8.setObjectName("entry8")
        self.gridLayout_3.addWidget(self.entry8, 1, 8, 1, 1)
        self.exit8 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exit8.sizePolicy().hasHeightForWidth())
        self.exit8.setSizePolicy(sizePolicy)
        self.exit8.setStyleSheet("border: 1px solid black")
        self.exit8.setText("")
        self.exit8.setObjectName("exit8")
        self.gridLayout_3.addWidget(self.exit8, 2, 8, 1, 1)
        self.share5 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.share5.sizePolicy().hasHeightForWidth())
        self.share5.setSizePolicy(sizePolicy)
        self.share5.setStyleSheet("border: 1px solid black")
        self.share5.setText("")
        self.share5.setObjectName("share5")
        self.gridLayout_3.addWidget(self.share5, 4, 5, 1, 1)
        self.time4 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time4.sizePolicy().hasHeightForWidth())
        self.time4.setSizePolicy(sizePolicy)
        self.time4.setStyleSheet("border: 1px solid black")
        self.time4.setText("")
        self.time4.setObjectName("time4")
        self.gridLayout_3.addWidget(self.time4, 3, 4, 1, 1)
        self.diff4 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.diff4.sizePolicy().hasHeightForWidth())
        self.diff4.setSizePolicy(sizePolicy)
        self.diff4.setStyleSheet("border: 1px solid black")
        self.diff4.setText("")
        self.diff4.setObjectName("diff4")
        self.gridLayout_3.addWidget(self.diff4, 5, 4, 1, 1)
        self.share2 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.share2.sizePolicy().hasHeightForWidth())
        self.share2.setSizePolicy(sizePolicy)
        self.share2.setStyleSheet("border: 1px solid black")
        self.share2.setText("")
        self.share2.setObjectName("share2")
        self.gridLayout_3.addWidget(self.share2, 4, 2, 1, 1)
        self.pl4 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pl4.sizePolicy().hasHeightForWidth())
        self.pl4.setSizePolicy(sizePolicy)
        self.pl4.setStyleSheet("border: 1px solid black")
        self.pl4.setText("")
        self.pl4.setObjectName("pl4")
        self.gridLayout_3.addWidget(self.pl4, 6, 4, 1, 1)
        self.entry7 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry7.sizePolicy().hasHeightForWidth())
        self.entry7.setSizePolicy(sizePolicy)
        self.entry7.setStyleSheet("border: 1px solid black")
        self.entry7.setText("")
        self.entry7.setObjectName("entry7")
        self.gridLayout_3.addWidget(self.entry7, 1, 7, 1, 1)
        self.pl5 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pl5.sizePolicy().hasHeightForWidth())
        self.pl5.setSizePolicy(sizePolicy)
        self.pl5.setStyleSheet("border: 1px solid black")
        self.pl5.setText("")
        self.pl5.setObjectName("pl5")
        self.gridLayout_3.addWidget(self.pl5, 6, 5, 1, 1)
        self.pl7 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pl7.sizePolicy().hasHeightForWidth())
        self.pl7.setSizePolicy(sizePolicy)
        self.pl7.setStyleSheet("border: 1px solid black")
        self.pl7.setText("")
        self.pl7.setObjectName("pl7")
        self.gridLayout_3.addWidget(self.pl7, 6, 7, 1, 1)
        self.exit1 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exit1.sizePolicy().hasHeightForWidth())
        self.exit1.setSizePolicy(sizePolicy)
        self.exit1.setStyleSheet("border: 1px solid black")
        self.exit1.setText("")
        self.exit1.setObjectName("exit1")
        self.gridLayout_3.addWidget(self.exit1, 2, 1, 1, 1)
        self.entryHead = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entryHead.sizePolicy().hasHeightForWidth())
        self.entryHead.setSizePolicy(sizePolicy)
        self.entryHead.setStyleSheet("")
        self.entryHead.setObjectName("entryHead")
        self.gridLayout_3.addWidget(self.entryHead, 1, 0, 1, 1)
        self.diff6 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.diff6.sizePolicy().hasHeightForWidth())
        self.diff6.setSizePolicy(sizePolicy)
        self.diff6.setStyleSheet("border: 1px solid black")
        self.diff6.setText("")
        self.diff6.setObjectName("diff6")
        self.gridLayout_3.addWidget(self.diff6, 5, 6, 1, 1)
        self.time6 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time6.sizePolicy().hasHeightForWidth())
        self.time6.setSizePolicy(sizePolicy)
        self.time6.setStyleSheet("border: 1px solid black")
        self.time6.setText("")
        self.time6.setObjectName("time6")
        self.gridLayout_3.addWidget(self.time6, 3, 6, 1, 1)
        self.pl2 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pl2.sizePolicy().hasHeightForWidth())
        self.pl2.setSizePolicy(sizePolicy)
        self.pl2.setStyleSheet("border: 1px solid black")
        self.pl2.setText("")
        self.pl2.setObjectName("pl2")
        self.gridLayout_3.addWidget(self.pl2, 6, 2, 1, 1)
        self.diff1 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.diff1.sizePolicy().hasHeightForWidth())
        self.diff1.setSizePolicy(sizePolicy)
        self.diff1.setStyleSheet("border: 1px solid black")
        self.diff1.setText("")
        self.diff1.setObjectName("diff1")
        self.gridLayout_3.addWidget(self.diff1, 5, 1, 1, 1)
        self.share3 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.share3.sizePolicy().hasHeightForWidth())
        self.share3.setSizePolicy(sizePolicy)
        self.share3.setStyleSheet("border: 1px solid black")
        self.share3.setText("")
        self.share3.setObjectName("share3")
        self.gridLayout_3.addWidget(self.share3, 4, 3, 1, 1)
        self.exit7 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exit7.sizePolicy().hasHeightForWidth())
        self.exit7.setSizePolicy(sizePolicy)
        self.exit7.setStyleSheet("border: 1px solid black")
        self.exit7.setText("")
        self.exit7.setObjectName("exit7")
        self.gridLayout_3.addWidget(self.exit7, 2, 7, 1, 1)
        self.time2 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time2.sizePolicy().hasHeightForWidth())
        self.time2.setSizePolicy(sizePolicy)
        self.time2.setStyleSheet("border: 1px solid black")
        self.time2.setText("")
        self.time2.setObjectName("time2")
        self.gridLayout_3.addWidget(self.time2, 3, 2, 1, 1)
        self.diff7 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.diff7.sizePolicy().hasHeightForWidth())
        self.diff7.setSizePolicy(sizePolicy)
        self.diff7.setStyleSheet("border: 1px solid black")
        self.diff7.setText("")
        self.diff7.setObjectName("diff7")
        self.gridLayout_3.addWidget(self.diff7, 5, 7, 1, 1)
        self.exit6 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exit6.sizePolicy().hasHeightForWidth())
        self.exit6.setSizePolicy(sizePolicy)
        self.exit6.setStyleSheet("border: 1px solid black")
        self.exit6.setText("")
        self.exit6.setObjectName("exit6")
        self.gridLayout_3.addWidget(self.exit6, 2, 6, 1, 1)
        self.time3 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time3.sizePolicy().hasHeightForWidth())
        self.time3.setSizePolicy(sizePolicy)
        self.time3.setStyleSheet("border: 1px solid black")
        self.time3.setText("")
        self.time3.setObjectName("time3")
        self.gridLayout_3.addWidget(self.time3, 3, 3, 1, 1)
        self.explain = QtWidgets.QTextEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.explain.sizePolicy().hasHeightForWidth())
        self.explain.setSizePolicy(sizePolicy)
        self.explain.setObjectName("explain")
        self.gridLayout_3.addWidget(self.explain, 7, 0, 1, 9)
        self.entry4 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry4.sizePolicy().hasHeightForWidth())
        self.entry4.setSizePolicy(sizePolicy)
        self.entry4.setStyleSheet("border: 1px solid black")
        self.entry4.setText("")
        self.entry4.setObjectName("entry4")
        self.gridLayout_3.addWidget(self.entry4, 1, 4, 1, 1)
        self.exitHead = QtWidgets.QLabel(self.layoutWidget)
        self.exitHead.setStyleSheet("")
        self.exitHead.setObjectName("exitHead")
        self.gridLayout_3.addWidget(self.exitHead, 2, 0, 1, 1)
        self.exit5 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exit5.sizePolicy().hasHeightForWidth())
        self.exit5.setSizePolicy(sizePolicy)
        self.exit5.setStyleSheet("border: 1px solid black")
        self.exit5.setText("")
        self.exit5.setObjectName("exit5")
        self.gridLayout_3.addWidget(self.exit5, 2, 5, 1, 1)
        self.diff3 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.diff3.sizePolicy().hasHeightForWidth())
        self.diff3.setSizePolicy(sizePolicy)
        self.diff3.setStyleSheet("border: 1px solid black")
        self.diff3.setText("")
        self.diff3.setObjectName("diff3")
        self.gridLayout_3.addWidget(self.diff3, 5, 3, 1, 1)
        self.time1 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time1.sizePolicy().hasHeightForWidth())
        self.time1.setSizePolicy(sizePolicy)
        self.time1.setStyleSheet("border: 1px solid black")
        self.time1.setText("")
        self.time1.setObjectName("time1")
        self.gridLayout_3.addWidget(self.time1, 3, 1, 1, 1)
        self.entry1 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry1.sizePolicy().hasHeightForWidth())
        self.entry1.setSizePolicy(sizePolicy)
        self.entry1.setStyleSheet("border: 1px solid black")
        self.entry1.setObjectName("entry1")
        self.gridLayout_3.addWidget(self.entry1, 1, 1, 1, 1)
        self.strategy = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.strategy.sizePolicy().hasHeightForWidth())
        self.strategy.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(24)
        self.strategy.setFont(font)
        self.strategy.setStyleSheet("border: 1px solid black")
        self.strategy.setObjectName("strategy")
        self.gridLayout_3.addWidget(self.strategy, 0, 3, 1, 3)
        self.time5 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time5.sizePolicy().hasHeightForWidth())
        self.time5.setSizePolicy(sizePolicy)
        self.time5.setStyleSheet("border: 1px solid black")
        self.time5.setText("")
        self.time5.setObjectName("time5")
        self.gridLayout_3.addWidget(self.time5, 3, 5, 1, 1)
        self.diff5 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.diff5.sizePolicy().hasHeightForWidth())
        self.diff5.setSizePolicy(sizePolicy)
        self.diff5.setStyleSheet("border: 1px solid black")
        self.diff5.setText("")
        self.diff5.setObjectName("diff5")
        self.gridLayout_3.addWidget(self.diff5, 5, 5, 1, 1)
        self.link = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.link.sizePolicy().hasHeightForWidth())
        self.link.setSizePolicy(sizePolicy)
        self.link.setStyleSheet("border: 1px solid black")
        self.link.setText("")
        self.link.setObjectName("link")
        self.gridLayout_3.addWidget(self.link, 0, 6, 1, 3)
        self.share7 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.share7.sizePolicy().hasHeightForWidth())
        self.share7.setSizePolicy(sizePolicy)
        self.share7.setStyleSheet("border: 1px solid black")
        self.share7.setText("")
        self.share7.setObjectName("share7")
        self.gridLayout_3.addWidget(self.share7, 4, 7, 1, 1)
        self.exit2 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exit2.sizePolicy().hasHeightForWidth())
        self.exit2.setSizePolicy(sizePolicy)
        self.exit2.setStyleSheet("border: 1px solid black")
        self.exit2.setText("")
        self.exit2.setObjectName("exit2")
        self.gridLayout_3.addWidget(self.exit2, 2, 2, 1, 1)
        self.diff2 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.diff2.sizePolicy().hasHeightForWidth())
        self.diff2.setSizePolicy(sizePolicy)
        self.diff2.setStyleSheet("border: 1px solid black")
        self.diff2.setText("")
        self.diff2.setObjectName("diff2")
        self.gridLayout_3.addWidget(self.diff2, 5, 2, 1, 1)
        self.exit3 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exit3.sizePolicy().hasHeightForWidth())
        self.exit3.setSizePolicy(sizePolicy)
        self.exit3.setStyleSheet("border: 1px solid black")
        self.exit3.setText("")
        self.exit3.setObjectName("exit3")
        self.gridLayout_3.addWidget(self.exit3, 2, 3, 1, 1)
        self.entry6 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry6.sizePolicy().hasHeightForWidth())
        self.entry6.setSizePolicy(sizePolicy)
        self.entry6.setStyleSheet("border: 1px solid black")
        self.entry6.setText("")
        self.entry6.setObjectName("entry6")
        self.gridLayout_3.addWidget(self.entry6, 1, 6, 1, 1)
        self.pl3 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pl3.sizePolicy().hasHeightForWidth())
        self.pl3.setSizePolicy(sizePolicy)
        self.pl3.setStyleSheet("border: 1px solid black")
        self.pl3.setText("")
        self.pl3.setObjectName("pl3")
        self.gridLayout_3.addWidget(self.pl3, 6, 3, 1, 1)
        self.pl6 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pl6.sizePolicy().hasHeightForWidth())
        self.pl6.setSizePolicy(sizePolicy)
        self.pl6.setStyleSheet("border: 1px solid black")
        self.pl6.setText("")
        self.pl6.setObjectName("pl6")
        self.gridLayout_3.addWidget(self.pl6, 6, 6, 1, 1)
        self.share8 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.share8.sizePolicy().hasHeightForWidth())
        self.share8.setSizePolicy(sizePolicy)
        self.share8.setStyleSheet("border: 1px solid black")
        self.share8.setText("")
        self.share8.setObjectName("share8")
        self.gridLayout_3.addWidget(self.share8, 4, 8, 1, 1)
        self.share6 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.share6.sizePolicy().hasHeightForWidth())
        self.share6.setSizePolicy(sizePolicy)
        self.share6.setStyleSheet("border: 1px solid black")
        self.share6.setText("")
        self.share6.setObjectName("share6")
        self.gridLayout_3.addWidget(self.share6, 4, 6, 1, 1)
        self.time8 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time8.sizePolicy().hasHeightForWidth())
        self.time8.setSizePolicy(sizePolicy)
        self.time8.setStyleSheet("border: 1px solid black")
        self.time8.setText("")
        self.time8.setObjectName("time8")
        self.gridLayout_3.addWidget(self.time8, 3, 8, 1, 1)
        self.pl_Head = QtWidgets.QLabel(self.layoutWidget)
        self.pl_Head.setStyleSheet("")
        self.pl_Head.setObjectName("pl_Head")
        self.gridLayout_3.addWidget(self.pl_Head, 6, 0, 1, 1)
        self.notes = QtWidgets.QTextEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notes.sizePolicy().hasHeightForWidth())
        self.notes.setSizePolicy(sizePolicy)
        self.notes.setObjectName("notes")
        self.gridLayout_3.addWidget(self.notes, 8, 0, 1, 9)
        self.timeHeadBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.timeHeadBtn.setMaximumSize(QtCore.QSize(50, 16777215))
        self.timeHeadBtn.setObjectName("timeHeadBtn")
        self.gridLayout_3.addWidget(self.timeHeadBtn, 3, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.chart1Btn = QtWidgets.QPushButton(self.layoutWidget)
        self.chart1Btn.setMaximumSize(QtCore.QSize(60, 16777215))
        self.chart1Btn.setObjectName("chart1Btn")
        self.horizontalLayout_3.addWidget(self.chart1Btn)
        self.chart1Start = QtWidgets.QDateTimeEdit(self.layoutWidget)
        self.chart1Start.setObjectName("chart1Start")
        self.horizontalLayout_3.addWidget(self.chart1Start)
        self.chart1End = QtWidgets.QDateTimeEdit(self.layoutWidget)
        self.chart1End.setObjectName("chart1End")
        self.horizontalLayout_3.addWidget(self.chart1End)
        self.chart1Interval = QtWidgets.QSpinBox(self.layoutWidget)
        self.chart1Interval.setMaximum(60)
        self.chart1Interval.setObjectName("chart1Interval")
        self.horizontalLayout_3.addWidget(self.chart1Interval)
        self.chart1Name = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chart1Name.sizePolicy().hasHeightForWidth())
        self.chart1Name.setSizePolicy(sizePolicy)
        self.chart1Name.setObjectName("chart1Name")
        self.horizontalLayout_3.addWidget(self.chart1Name)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.chart1 = ClickLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chart1.sizePolicy().hasHeightForWidth())
        self.chart1.setSizePolicy(sizePolicy)
        self.chart1.setMinimumSize(QtCore.QSize(1000, 0))
        self.chart1.setMouseTracking(True)
        self.chart1.setAcceptDrops(True)
        self.chart1.setStyleSheet("border: 1px solid black")
        self.chart1.setText("")
        self.chart1.setPixmap(QtGui.QPixmap("../../images/ZeroSubstanceCreation.png"))
        self.chart1.setObjectName("chart1")
        self.verticalLayout_4.addWidget(self.chart1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(70, 90, 1191, 16))
        self.line.setLineWidth(3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(71, 10, 1298, 82))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout.setObjectName("gridLayout")
        self.infileEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.infileEdit.sizePolicy().hasHeightForWidth())
        self.infileEdit.setSizePolicy(sizePolicy)
        self.infileEdit.setMinimumSize(QtCore.QSize(400, 0))
        self.infileEdit.setObjectName("infileEdit")
        self.gridLayout.addWidget(self.infileEdit, 1, 1, 1, 2)
        self.tradeList = QtWidgets.QComboBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tradeList.sizePolicy().hasHeightForWidth())
        self.tradeList.setSizePolicy(sizePolicy)
        self.tradeList.setObjectName("tradeList")
        self.gridLayout.addWidget(self.tradeList, 3, 0, 1, 2)
        self.dateEdit = QtWidgets.QDateEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.dateEdit.setFont(font)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout.addWidget(self.dateEdit, 3, 2, 1, 1)
        self.inFileBtn = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inFileBtn.sizePolicy().hasHeightForWidth())
        self.inFileBtn.setSizePolicy(sizePolicy)
        self.inFileBtn.setMaximumSize(QtCore.QSize(50, 16777215))
        self.inFileBtn.setObjectName("inFileBtn")
        self.gridLayout.addWidget(self.inFileBtn, 1, 0, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.dasImport = QtWidgets.QRadioButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dasImport.sizePolicy().hasHeightForWidth())
        self.dasImport.setSizePolicy(sizePolicy)
        self.dasImport.setObjectName("dasImport")
        self.verticalLayout_3.addWidget(self.dasImport)
        self.ibImport = QtWidgets.QRadioButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ibImport.sizePolicy().hasHeightForWidth())
        self.ibImport.setSizePolicy(sizePolicy)
        self.ibImport.setObjectName("ibImport")
        self.verticalLayout_3.addWidget(self.ibImport)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.goBtn = QtWidgets.QPushButton(self.layoutWidget1)
        self.goBtn.setObjectName("goBtn")
        self.horizontalLayout_4.addWidget(self.goBtn)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_4)
        self.textBrowser = QtWidgets.QTextBrowser(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setMinimumSize(QtCore.QSize(450, 80))
        self.textBrowser.setMaximumSize(QtCore.QSize(16777215, 80))
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout_7.addWidget(self.textBrowser)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(74, 803, 1897, 670))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.chart2Btn = QtWidgets.QPushButton(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chart2Btn.sizePolicy().hasHeightForWidth())
        self.chart2Btn.setSizePolicy(sizePolicy)
        self.chart2Btn.setMaximumSize(QtCore.QSize(60, 16777215))
        self.chart2Btn.setObjectName("chart2Btn")
        self.horizontalLayout_5.addWidget(self.chart2Btn)
        self.chart2Start = QtWidgets.QDateTimeEdit(self.layoutWidget2)
        self.chart2Start.setObjectName("chart2Start")
        self.horizontalLayout_5.addWidget(self.chart2Start)
        self.chart2End = QtWidgets.QDateTimeEdit(self.layoutWidget2)
        self.chart2End.setObjectName("chart2End")
        self.horizontalLayout_5.addWidget(self.chart2End)
        self.chart2Interval = QtWidgets.QSpinBox(self.layoutWidget2)
        self.chart2Interval.setMaximum(60)
        self.chart2Interval.setObjectName("chart2Interval")
        self.horizontalLayout_5.addWidget(self.chart2Interval)
        self.chart2Name = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chart2Name.sizePolicy().hasHeightForWidth())
        self.chart2Name.setSizePolicy(sizePolicy)
        self.chart2Name.setObjectName("chart2Name")
        self.horizontalLayout_5.addWidget(self.chart2Name)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.chart2 = ClickLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chart2.sizePolicy().hasHeightForWidth())
        self.chart2.setSizePolicy(sizePolicy)
        self.chart2.setMinimumSize(QtCore.QSize(500, 0))
        self.chart2.setStyleSheet("border: 1px solid black")
        self.chart2.setText("")
        self.chart2.setPixmap(QtGui.QPixmap("../../images/ZeroSubstanceCreation.png"))
        self.chart2.setObjectName("chart2")
        self.verticalLayout_6.addWidget(self.chart2)
        self.horizontalLayout_6.addLayout(self.verticalLayout_6)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.chart3Btn = QtWidgets.QPushButton(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chart3Btn.sizePolicy().hasHeightForWidth())
        self.chart3Btn.setSizePolicy(sizePolicy)
        self.chart3Btn.setMaximumSize(QtCore.QSize(60, 16777215))
        self.chart3Btn.setObjectName("chart3Btn")
        self.horizontalLayout.addWidget(self.chart3Btn)
        self.chart3Start = QtWidgets.QDateTimeEdit(self.layoutWidget2)
        self.chart3Start.setObjectName("chart3Start")
        self.horizontalLayout.addWidget(self.chart3Start)
        self.chart3End = QtWidgets.QDateTimeEdit(self.layoutWidget2)
        self.chart3End.setObjectName("chart3End")
        self.horizontalLayout.addWidget(self.chart3End)
        self.chart3Interval = QtWidgets.QSpinBox(self.layoutWidget2)
        self.chart3Interval.setMaximum(60)
        self.chart3Interval.setObjectName("chart3Interval")
        self.horizontalLayout.addWidget(self.chart3Interval)
        self.chart3Name = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chart3Name.sizePolicy().hasHeightForWidth())
        self.chart3Name.setSizePolicy(sizePolicy)
        self.chart3Name.setObjectName("chart3Name")
        self.horizontalLayout.addWidget(self.chart3Name)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.chart3 = ClickLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chart3.sizePolicy().hasHeightForWidth())
        self.chart3.setSizePolicy(sizePolicy)
        self.chart3.setMinimumSize(QtCore.QSize(500, 0))
        self.chart3.setStyleSheet("border: 1px solid black")
        self.chart3.setText("")
        self.chart3.setPixmap(QtGui.QPixmap("../../images/ZeroSubstanceCreation.png"))
        self.chart3.setObjectName("chart3")
        self.verticalLayout_5.addWidget(self.chart3)
        self.horizontalLayout_6.addLayout(self.verticalLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 2334, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionFileSettings = QtWidgets.QAction(MainWindow)
        self.actionFileSettings.setObjectName("actionFileSettings")
        self.actionChart_Settings = QtWidgets.QAction(MainWindow)
        self.actionChart_Settings.setObjectName("actionChart_Settings")
        self.menuFile.addAction(self.actionFileSettings)
        self.menuFile.addAction(self.actionChart_Settings)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "Stock Name"))
        self.plHead.setText(_translate("MainWindow", "P / L"))
        self.pl.setText(_translate("MainWindow", "345.67"))
        self.startHead.setText(_translate("MainWindow", "Start"))
        self.start.setText(_translate("MainWindow", "345.67"))
        self.durHead.setText(_translate("MainWindow", "Dur"))
        self.dur.setText(_translate("MainWindow", "345.67"))
        self.posHead.setText(_translate("MainWindow", "Pos"))
        self.pos.setText(_translate("MainWindow", "750 Shares"))
        self.mktHead.setText(_translate("MainWindow", "Mkt"))
        self.mkt.setText(_translate("MainWindow", "345.67"))
        self.targHead.setText(_translate("MainWindow", "Targ"))
        self.targ.setText(_translate("MainWindow", "45.67"))
        self.stopHead.setText(_translate("MainWindow", "Stop"))
        self.stop.setText(_translate("MainWindow", "43.00"))
        self.rrHead.setText(_translate("MainWindow", "R:R"))
        self.maxHead.setText(_translate("MainWindow", "Max\n"
"Loss"))
        self.lostHead.setText(_translate("MainWindow", "Amt\n"
"Lost"))
        self.lost.setText(_translate("MainWindow", "43.00"))
        self.sumNote.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">summary note</span></p></body></html>"))
        self.account.setText(_translate("MainWindow", "Account"))
        self.diffHead.setText(_translate("MainWindow", "Diff"))
        self.shareHead.setText(_translate("MainWindow", "Share"))
        self.entryHead.setText(_translate("MainWindow", "Entry:"))
        self.exitHead.setText(_translate("MainWindow", "Exit:"))
        self.entry1.setText(_translate("MainWindow", "43.50"))
        self.strategy.setText(_translate("MainWindow", "Strategy"))
        self.pl_Head.setText(_translate("MainWindow", "PL:"))
        self.timeHeadBtn.setText(_translate("MainWindow", "Time:"))
        self.chart1Btn.setText(_translate("MainWindow", "Update"))
        self.chart1Interval.setToolTip(_translate("MainWindow", "<html><head/><body><h3 style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:large; font-weight:600; color:#2d04fa;\">Set Candle Interval Size.</span></h3></body></html>"))
        self.chart1Name.setText(_translate("MainWindow", "TextLabel"))
        self.inFileBtn.setText(_translate("MainWindow", "In File"))
        self.dasImport.setText(_translate("MainWindow", "DAS import"))
        self.ibImport.setText(_translate("MainWindow", "IB import"))
        self.goBtn.setToolTip(_translate("MainWindow", "<html><head/><body><p>Run the file shown in the edit box  and load up the chosen charts in the check boxes.</p></body></html>"))
        self.goBtn.setText(_translate("MainWindow", "GO"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:7pt; color:#22aa44;\">To do exceptionally well you have to push your limits and that, if you push your limits, you will crash, and it will hurt a lot. You will think that you have failed--but that won\'t be true unless you give up. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:7pt; color:#22aa44;\">    Ray Dalio, founder Bridgewater assoc</span></p></body></html>"))
        self.chart2Btn.setText(_translate("MainWindow", "Update"))
        self.chart2Interval.setToolTip(_translate("MainWindow", "<html><head/><body><h3 style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:large; font-weight:600; color:#2d04fa;\">Set Candle Interval Size</span></h3></body></html>"))
        self.chart2Name.setText(_translate("MainWindow", "TextLabel"))
        self.chart3Btn.setText(_translate("MainWindow", "Update"))
        self.chart3Interval.setToolTip(_translate("MainWindow", "<html><head/><body><h3 style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:large; font-weight:600; color:#2d04fa;\">Set candle Interval Size</span></h3></body></html>"))
        self.chart3Name.setText(_translate("MainWindow", "TextLabel"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionFileSettings.setText(_translate("MainWindow", "File Settings"))
        self.actionFileSettings.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionChart_Settings.setText(_translate("MainWindow", "Chart Settings"))


from journal.view.clicklabel import ClickLabel
