# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\filesettings.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(995, 892)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/ZSLogo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(31, 1, 276, 33))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(33, 43, 926, 826))
        self.widget.setObjectName("widget")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.journalBtn = QtWidgets.QPushButton(self.widget)
        self.journalBtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.journalBtn.setObjectName("journalBtn")
        self.horizontalLayout.addWidget(self.journalBtn)
        self.journal = QtWidgets.QLineEdit(self.widget)
        self.journal.setMinimumSize(QtCore.QSize(300, 0))
        self.journal.setObjectName("journal")
        self.horizontalLayout.addWidget(self.journal)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.schemeBtn = QtWidgets.QPushButton(self.widget)
        self.schemeBtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.schemeBtn.setObjectName("schemeBtn")
        self.horizontalLayout_2.addWidget(self.schemeBtn)
        self.scheme = QtWidgets.QLineEdit(self.widget)
        self.scheme.setMinimumSize(QtCore.QSize(300, 0))
        self.scheme.setObjectName("scheme")
        self.horizontalLayout_2.addWidget(self.scheme)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.schemeLbl = QtWidgets.QLabel(self.widget)
        self.schemeLbl.setObjectName("schemeLbl")
        self.verticalLayout_2.addWidget(self.schemeLbl)
        spacerItem1 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.dasInfileBtn = QtWidgets.QPushButton(self.widget)
        self.dasInfileBtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dasInfileBtn.setObjectName("dasInfileBtn")
        self.horizontalLayout_3.addWidget(self.dasInfileBtn)
        self.dasInfile = QtWidgets.QLineEdit(self.widget)
        self.dasInfile.setMinimumSize(QtCore.QSize(300, 0))
        self.dasInfile.setObjectName("dasInfile")
        self.horizontalLayout_3.addWidget(self.dasInfile)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.dasInfileLbl = QtWidgets.QLabel(self.widget)
        self.dasInfileLbl.setObjectName("dasInfileLbl")
        self.verticalLayout_2.addWidget(self.dasInfileLbl)
        spacerItem2 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.dasInfile2Btn = QtWidgets.QPushButton(self.widget)
        self.dasInfile2Btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dasInfile2Btn.setObjectName("dasInfile2Btn")
        self.horizontalLayout_4.addWidget(self.dasInfile2Btn)
        self.dasInfile2 = QtWidgets.QLineEdit(self.widget)
        self.dasInfile2.setMinimumSize(QtCore.QSize(300, 0))
        self.dasInfile2.setObjectName("dasInfile2")
        self.horizontalLayout_4.addWidget(self.dasInfile2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.dasInfile2Lbl = QtWidgets.QLabel(self.widget)
        self.dasInfile2Lbl.setObjectName("dasInfile2Lbl")
        self.verticalLayout_2.addWidget(self.dasInfile2Lbl)
        spacerItem3 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.label_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ibInfileBtn = QtWidgets.QPushButton(self.widget)
        self.ibInfileBtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ibInfileBtn.setObjectName("ibInfileBtn")
        self.horizontalLayout_5.addWidget(self.ibInfileBtn)
        self.ibInfile = QtWidgets.QLineEdit(self.widget)
        self.ibInfile.setObjectName("ibInfile")
        self.horizontalLayout_5.addWidget(self.ibInfile)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.ibInfileLbl = QtWidgets.QLabel(self.widget)
        self.ibInfileLbl.setObjectName("ibInfileLbl")
        self.verticalLayout_2.addWidget(self.ibInfileLbl)
        spacerItem4 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.label_5 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.outdirDefault = QtWidgets.QRadioButton(self.widget)
        self.outdirDefault.setObjectName("outdirDefault")
        self.verticalLayout.addWidget(self.outdirDefault)
        self.outdirStatic = QtWidgets.QRadioButton(self.widget)
        self.outdirStatic.setObjectName("outdirStatic")
        self.verticalLayout.addWidget(self.outdirStatic)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.outdir = QtWidgets.QLineEdit(self.widget)
        self.outdir.setMinimumSize(QtCore.QSize(300, 0))
        self.outdir.setObjectName("outdir")
        self.horizontalLayout_6.addWidget(self.outdir)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.outdirLbl = QtWidgets.QLabel(self.widget)
        self.outdirLbl.setObjectName("outdirLbl")
        self.verticalLayout_2.addWidget(self.outdirLbl)
        spacerItem5 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.label_6 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.disciplinedBtn = QtWidgets.QPushButton(self.widget)
        self.disciplinedBtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.disciplinedBtn.setObjectName("disciplinedBtn")
        self.horizontalLayout_9.addWidget(self.disciplinedBtn)
        self.disciplinedEdit = QtWidgets.QLineEdit(self.widget)
        self.disciplinedEdit.setMinimumSize(QtCore.QSize(300, 0))
        self.disciplinedEdit.setText("")
        self.disciplinedEdit.setObjectName("disciplinedEdit")
        self.horizontalLayout_9.addWidget(self.disciplinedEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        spacerItem6 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.explainDateLbl = QtWidgets.QLabel(self.widget)
        self.explainDateLbl.setObjectName("explainDateLbl")
        self.verticalLayout_2.addWidget(self.explainDateLbl)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.theDateBtn = QtWidgets.QPushButton(self.widget)
        self.theDateBtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.theDateBtn.setObjectName("theDateBtn")
        self.horizontalLayout_7.addWidget(self.theDateBtn)
        self.theDate = QtWidgets.QDateEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.theDate.sizePolicy().hasHeightForWidth())
        self.theDate.setSizePolicy(sizePolicy)
        self.theDate.setObjectName("theDate")
        self.horizontalLayout_7.addWidget(self.theDate)
        self.theDateCbox = QtWidgets.QCheckBox(self.widget)
        self.theDateCbox.setFocusPolicy(QtCore.Qt.TabFocus)
        self.theDateCbox.setChecked(False)
        self.theDateCbox.setObjectName("theDateCbox")
        self.horizontalLayout_7.addWidget(self.theDateCbox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.okBtn = QtWidgets.QPushButton(self.widget)
        self.okBtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.okBtn.setObjectName("okBtn")
        self.horizontalLayout_8.addWidget(self.okBtn)
        spacerItem7 = QtWidgets.QSpacerItem(228, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_15.addLayout(self.verticalLayout_2)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem8)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.structjourDbBtn = QtWidgets.QPushButton(self.widget)
        self.structjourDbBtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.structjourDbBtn.setObjectName("structjourDbBtn")
        self.horizontalLayout_10.addWidget(self.structjourDbBtn)
        self.structjourDbEdit = QtWidgets.QLineEdit(self.widget)
        self.structjourDbEdit.setMinimumSize(QtCore.QSize(300, 0))
        self.structjourDbEdit.setText("")
        self.structjourDbEdit.setObjectName("structjourDbEdit")
        self.horizontalLayout_10.addWidget(self.structjourDbEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.verticalLayout_11.addLayout(self.verticalLayout_3)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        spacerItem9 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem9)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.label_8)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.tradeDbBtn = QtWidgets.QPushButton(self.widget)
        self.tradeDbBtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tradeDbBtn.setObjectName("tradeDbBtn")
        self.horizontalLayout_11.addWidget(self.tradeDbBtn)
        self.tradeDbEdit = QtWidgets.QLineEdit(self.widget)
        self.tradeDbEdit.setMinimumSize(QtCore.QSize(300, 0))
        self.tradeDbEdit.setText("")
        self.tradeDbEdit.setObjectName("tradeDbEdit")
        self.horizontalLayout_11.addWidget(self.tradeDbEdit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.verticalLayout_10.addLayout(self.verticalLayout_4)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem10 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem10)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_10 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_5.addWidget(self.label_10)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.createDirsBtn = QtWidgets.QPushButton(self.widget)
        self.createDirsBtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.createDirsBtn.setObjectName("createDirsBtn")
        self.horizontalLayout_12.addWidget(self.createDirsBtn)
        self.createDirsYear = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.createDirsYear.sizePolicy().hasHeightForWidth())
        self.createDirsYear.setSizePolicy(sizePolicy)
        self.createDirsYear.setMaximumSize(QtCore.QSize(75, 16777215))
        self.createDirsYear.setObjectName("createDirsYear")
        self.createDirsYear.addItem("")
        self.createDirsYear.addItem("")
        self.createDirsYear.addItem("")
        self.createDirsYear.addItem("")
        self.createDirsYear.addItem("")
        self.createDirsYear.addItem("")
        self.createDirsYear.addItem("")
        self.horizontalLayout_12.addWidget(self.createDirsYear)
        self.createDirsMonth = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.createDirsMonth.sizePolicy().hasHeightForWidth())
        self.createDirsMonth.setSizePolicy(sizePolicy)
        self.createDirsMonth.setMaximumSize(QtCore.QSize(85, 16777215))
        self.createDirsMonth.setObjectName("createDirsMonth")
        self.createDirsMonth.addItem("")
        self.createDirsMonth.addItem("")
        self.createDirsMonth.addItem("")
        self.createDirsMonth.addItem("")
        self.createDirsMonth.addItem("")
        self.createDirsMonth.addItem("")
        self.createDirsMonth.addItem("")
        self.createDirsMonth.addItem("")
        self.createDirsMonth.addItem("")
        self.createDirsMonth.addItem("")
        self.createDirsMonth.addItem("")
        self.createDirsMonth.addItem("")
        self.horizontalLayout_12.addWidget(self.createDirsMonth)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_11.addLayout(self.verticalLayout_6)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        spacerItem11 = QtWidgets.QSpacerItem(401, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem11)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_12 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_7.addWidget(self.label_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.logfile_browse = QtWidgets.QPushButton(self.widget)
        self.logfile_browse.setFocusPolicy(QtCore.Qt.NoFocus)
        self.logfile_browse.setObjectName("logfile_browse")
        self.horizontalLayout_13.addWidget(self.logfile_browse)
        self.logfile_edit = QtWidgets.QLineEdit(self.widget)
        self.logfile_edit.setMinimumSize(QtCore.QSize(300, 0))
        self.logfile_edit.setText("")
        self.logfile_edit.setObjectName("logfile_edit")
        self.horizontalLayout_13.addWidget(self.logfile_edit)
        self.verticalLayout_7.addLayout(self.horizontalLayout_13)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_13 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_14.addWidget(self.label_13)
        self.logfile_level_cb = QtWidgets.QComboBox(self.widget)
        self.logfile_level_cb.setObjectName("logfile_level_cb")
        self.logfile_level_cb.addItem("")
        self.logfile_level_cb.addItem("")
        self.logfile_level_cb.addItem("")
        self.logfile_level_cb.addItem("")
        self.logfile_level_cb.addItem("")
        self.horizontalLayout_14.addWidget(self.logfile_level_cb)
        self.verticalLayout_8.addLayout(self.horizontalLayout_14)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.verticalLayout_11.addLayout(self.verticalLayout_9)
        self.verticalLayout_12.addLayout(self.verticalLayout_11)
        spacerItem12 = QtWidgets.QSpacerItem(20, 428, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem12)
        self.horizontalLayout_15.addLayout(self.verticalLayout_12)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "File Settings"))
        self.label_9.setText(_translate("Dialog", "Files and Directories"))
        self.journalBtn.setText(_translate("Dialog", "Journal Directory"))
        self.journal.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; color:#020761;\">The location you choose will hold files and directories organized by dates.</span></p></body></html>"))
        self.journal.setText(_translate("Dialog", "C:/traders/journal/"))
        self.label.setText(_translate("Dialog", "Directory Naming Scheme. "))
        self.schemeBtn.setText(_translate("Dialog", "Set Default"))
        self.scheme.setToolTip(_translate("Dialog", "<html><head/><body><p>Use the date variables as seen in the default naming scheme and see the result below. Please retain a month/day directory structure. Both directories should sort alpa-numerically. After editing press enter to update the naming scheme.</p></body></html>"))
        self.scheme.setText(_translate("Dialog", "_{Year}{month}_{MONTH}/_{month}{day}_{DAY}/"))
        self.schemeLbl.setText(_translate("Dialog", "_201901_January/_0114_Monday"))
        self.label_2.setText(_translate("Dialog", "DAS Trades export file"))
        self.dasInfileBtn.setToolTip(_translate("Dialog", "<html><head/><body><p>Click this button to return the edit box to just the file name.</p></body></html>"))
        self.dasInfileBtn.setText(_translate("Dialog", "DAS Trades export"))
        self.dasInfile.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; color:#000767;\">This is an export from the DAS Trader Pro trades window. Enter only the filename (exclude the path).</span></p></body></html>"))
        self.dasInfile.setText(_translate("Dialog", "trades.csv"))
        self.dasInfileLbl.setText(_translate("Dialog", "C:/traders/journal/_2019_January_0114_Monday/trades.csv"))
        self.label_3.setText(_translate("Dialog", "DAS positions export file"))
        self.dasInfile2Btn.setText(_translate("Dialog", "DAS positions export"))
        self.dasInfile2.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; color:#08056c;\">This is an export from DAS trader pro of the positions window.</span></p></body></html>"))
        self.dasInfile2.setText(_translate("Dialog", "positions.csv"))
        self.dasInfile2Lbl.setText(_translate("Dialog", "C:/traders/journal/_2019_January_0114_Monday/positions.csv"))
        self.label_4.setText(_translate("Dialog", "IB statement file pattern"))
        self.ibInfileBtn.setText(_translate("Dialog", "IB Activity Statement"))
        self.ibInfile.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:large; font-weight:600; color:#021581;\">Using the (simplified) globular {*}</span></p><p><span style=\" font-size:10pt;\">Use the </span><span style=\" font-size:10pt; font-weight:600;\">{*}</span><span style=\" font-size:10pt;\"> to replace any characters.</span></p><p><span style=\" font-size:10pt; font-weight:600;\">Activity{*}.html</span><span style=\" font-size:10pt;\"> will match </span><span style=\" font-size:10pt; font-weight:600;\">ActivityStatementU1234567.html</span></p><p><span style=\" font-size:10pt; font-weight:600;\">Activity{*}0904{*}.html</span><span style=\" font-size:10pt;\"> would match </span><span style=\" font-size:10pt; font-weight:600;\">ActivityStatement.20190904.html</span></p><p><span style=\" font-size:10pt; font-weight:600;\">{*}.html</span><span style=\" font-size:10pt;\"> will show all files ending in html</span></p><p><span style=\" font-size:10pt;\">Press enter or tab or click on a different object to see the results below.</span></p></body></html>"))
        self.ibInfile.setText(_translate("Dialog", "{*}Activity{*}.csv"))
        self.ibInfileLbl.setText(_translate("Dialog", "C:/traders/journal/_2019_January_0114_Monday/Activity_20190104.html"))
        self.label_5.setText(_translate("Dialog", "Output directory"))
        self.outdirDefault.setText(_translate("Dialog", "Default"))
        self.outdirStatic.setText(_translate("Dialog", "Static"))
        self.outdir.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; color:#040e6a;\">By default, the output dir will be below the indir. Recommend generally to keep default. Output files and charts will be saved to this directory.</span></p></body></html>"))
        self.outdir.setText(_translate("Dialog", "out/"))
        self.outdirLbl.setText(_translate("Dialog", "C:/traders/journal/_2019_January_0114_Monday/out/"))
        self.label_6.setText(_translate("Dialog", "Disciplined Trader log location"))
        self.disciplinedBtn.setText(_translate("Dialog", "Disciplined"))
        self.explainDateLbl.setText(_translate("Dialog", "Date will be used to locate daily directories and set dates if missing (DAS trade)"))
        self.theDateBtn.setText(_translate("Dialog", "Set to Today"))
        self.theDate.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" color:#042170;\">Change the date to update the directories on this form.</span></p></body></html>"))
        self.theDateCbox.setText(_translate("Dialog", "Set today when program opens."))
        self.okBtn.setText(_translate("Dialog", "OK"))
        self.label_7.setText(_translate("Dialog", "structjour database"))
        self.structjourDbBtn.setText(_translate("Dialog", "structjour db"))
        self.label_8.setText(_translate("Dialog", "trades database"))
        self.tradeDbBtn.setText(_translate("Dialog", "trade db"))
        self.label_10.setText(_translate("Dialog", "Create journal file directories for the month of ...."))
        self.createDirsBtn.setText(_translate("Dialog", "Create Dirs"))
        self.createDirsYear.setItemText(0, _translate("Dialog", "2019"))
        self.createDirsYear.setItemText(1, _translate("Dialog", "2020"))
        self.createDirsYear.setItemText(2, _translate("Dialog", "2021"))
        self.createDirsYear.setItemText(3, _translate("Dialog", "2022"))
        self.createDirsYear.setItemText(4, _translate("Dialog", "2023"))
        self.createDirsYear.setItemText(5, _translate("Dialog", "2024"))
        self.createDirsYear.setItemText(6, _translate("Dialog", "2025"))
        self.createDirsMonth.setItemText(0, _translate("Dialog", "January"))
        self.createDirsMonth.setItemText(1, _translate("Dialog", "February"))
        self.createDirsMonth.setItemText(2, _translate("Dialog", "March"))
        self.createDirsMonth.setItemText(3, _translate("Dialog", "April"))
        self.createDirsMonth.setItemText(4, _translate("Dialog", "May"))
        self.createDirsMonth.setItemText(5, _translate("Dialog", "June"))
        self.createDirsMonth.setItemText(6, _translate("Dialog", "July"))
        self.createDirsMonth.setItemText(7, _translate("Dialog", "August"))
        self.createDirsMonth.setItemText(8, _translate("Dialog", "September"))
        self.createDirsMonth.setItemText(9, _translate("Dialog", "October"))
        self.createDirsMonth.setItemText(10, _translate("Dialog", "November"))
        self.createDirsMonth.setItemText(11, _translate("Dialog", "December"))
        self.label_12.setText(_translate("Dialog", "Set log file and level"))
        self.logfile_browse.setText(_translate("Dialog", "Set log file"))
        self.label_13.setText(_translate("Dialog", "Choose log level"))
        self.logfile_level_cb.setItemText(0, _translate("Dialog", "Debug"))
        self.logfile_level_cb.setItemText(1, _translate("Dialog", "Info"))
        self.logfile_level_cb.setItemText(2, _translate("Dialog", "Warning"))
        self.logfile_level_cb.setItemText(3, _translate("Dialog", "Error"))
        self.logfile_level_cb.setItemText(4, _translate("Dialog", "Critical"))
